version: '3'
services:
    bot:
        build: .
        network_mode: host
        depends_on:
            - redis
        restart: on-failure
    redis:
        image: redis:latest
        logging:
            driver: none
        network_mode: host
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - redis-data:/data
        restart: on-failure
volumes:
    redis-data: